#!/bin/sh
: ${CIM_HOME:="/home/kim/.cim"}
export CIM_HOME
PATH="$CIM_HOME/bin:$PATH";export PATH
rm -f "$CIM_HOME/config/current"
[ -s "$CIM_HOME/config/default" ] && cp "$CIM_HOME/config/default" "$CIM_HOME/config/current"
. "$CIM_HOME/scripts/cim"

