#!/bin/sh -
# This file is for load

cim(){
    command="$1"
    shift
    case "$command" in
	install)
	    sh "$CIM_HOME/scripts/cim_install_impl" "$@" ;;
	use)
	    # To enable to affect ENV, file should be loaded rather than executed
	    . "$CIM_HOME/scripts/cim_use_impl" ;;
	resume)
		case "$1" in
		    rm)
			shift
			sh "$CIM_HOME/scripts/cim_resume" "rm" "$@" ;;
		    *)
			sh "$CIM_HOME/scripts/cim_resume" "resume" "$@" ;;
		esac;;
	reset)
	    sh "$CIM_HOME/scripts/cim_reset";;
	list)
	    case "$1" in
		install)
		    cat "$CIM_HOME/res/known" ;;
		resume)
		    echo "$CIM_HOME/res/resume-"* | sed 's/.*resume-//g';;
		use)
		    echo "$CIM_HOME/bin/"* | grep -v '[:alpha:]$';;
		*)
		    echo "Unknown subcommand '$1'. See 'cim help list'" >&2
		    return 1;;
	    esac
	    ;;
	help)
	    case "$1" in
		"")
		    cat "$CIM_HOME/res/help" ;;
		*)
		    if [ -s "$CIM_HOME/res/help_$1" ];then
			cat "$CIM_HOME/res/help_$1"
		    else
			echo "Help for $1 did not found. Exit." >&2
			return 1
		    fi
		    ;;
	    esac
	    ;;

	*)
	    cim help
	    echo "[0;31mUnknown command '$command'.[0;39m" >&2
	    return 1;;
    esac
}
