#!/bin/sh -
# This file is for execute
if [ $# -gt 0 ];then
    command="$1"
    shift
    if [ -s "$CIM_HOME/scripts/cim_cmd_$command" ];then
	sh "$CIM_HOME/scripts/cim_cmd_$command" "$@"
    else
	sh "$CIM_HOME/scripts/cim_cmd_unknown" "$command" "$@"
    fi
else
    sh "$CIM_HOME/scripts/cim_cmd_help"
fi
