#!/bin/sh -
. "$CIM_HOME/scripts/cim_utils"
case "$1" in
    "")
	cat "$CIM_HOME/doc/cim-help" ;;
    *)
	if [ -s "$CIM_HOME/doc/man/man1/cim-$1.1" ];then
            man "$CIM_HOME/doc/man/man1/cim-$1.1"
	else
	    cim_error "Help for '$1' is not prepared, sorry."
	    return 1
	fi
	;;
esac
