#!/bin/sh
set -e

__cim_split_impl_version(){
    impl=`echo $impl_with_version |  awk -F- '{print $1}'`
    version=`echo $impl_with_version | awk -F- '{print $2}'`
    echo $impl ${version:-`cat $cim_res_path/known | awk "/^$impl\\[/{match(\\$0, /[[:digit:].]+/);print substr(\\$0, RSTART, RLENGTH) }"`}
    unset impl version
}
__cim_get_download_path(){
    case $1 in
	clisp)
	    echo http://ftp.gnu.org/pub/gnu/clisp/release/$2/clisp-$2.tar.gz
	    ;;
	gcl)
	    echo ftp://ftp.gnu.org/pub/gnu/gcl/gcl-$2.tar.gz
	    ;;
	ecl)
	    echo http://downloads.sourceforge.net/project/ecls/ecls/${2%.*}/ecl-${2}.tgz
	    ;;
	*)
	    echo "unsupported" >&2;
	    return 1
	    ;;
    esac
}
cim_start_impl_install(){
    echo "cim_start_impl_install $1 $2" > $cim_tmp_path/resume-$1-$2
    [ -d $cim_impls_path/$impl-$version ] && echo "It seems you have installed clisp-$2. Did you mean 'cim reinstall $1-$2'?." >&2 && return 1
    cim_download_impl $1 $2
}
cim_download_impl(){
    echo "cim_download_impl $1 $2" > $cim_tmp_path/resume-$1-$2
    impl_archive=$cim_archives_path/$1-$2.tar.gz
    rm -rf $impl_archive
    if [ -f $impl_archive ] || (curl -L `__cim_get_download_path $impl $version` -o $impl_archive  && [ -f $impl_archive ])
    then
	unset impl_archive
	cim_expand_impl $1 $2
    else
	unset impl_archive
	echo "Failed to Donwload. Exit" >&2
	return 1
    fi
}

cim_expand_impl(){
    echo "cim_expand_impl $1 $2" > $cim_tmp_path/resume-$1-$2
    rm -rf  $cim_src_path/$1-$2
    gzip -dc $cim_archives_path/$1-$2.tar.gz | tar xf - -C $cim_src_path
    [ "$1" = gcl ] && mv $cim_src_path/gcl $cim_src_path/gcl-$2
    cim_configure_impl $1 $2
}

cim_configure_impl(){
    echo "cim_configure_impl $1 $2" > $cim_tmp_path/resume-$1-$2
    (cd $cim_src_path/$1-$2 && ./configure --prefix=$cim_impls_path/$1-$2)
    cim_make_impl $1 $2
}
cim_make_impl(){
    echo "cim_make_impl $1 $2" > $cim_tmp_path/resume-$1-$2
    cd $cim_src_path/$1-$2
    (cd $cim_src_path/$1-$2 && make)
    cim_install_impl $1 $2
}
cim_install_impl(){
    echo "cim_install_impl $1 $2" > $cim_tmp_path/resume-$1-$2
    install_dir=$cim_impls_path/$1-$2
    mkdir -p $install_dir
    (cd $cim_src_path/$1-$2 && make install)
    cim_finish_install_impl $1 $2
}
cim_finish_install_impl(){
    echo "cim_finish_install_impl $1 $2" > $cim_tmp_path/resume-$1-$2
    ln -s $cim_impls_path/$1-$2/bin/$1 $cim_bin_path/$1-$2
    [ -n `ls $cim_bin_path/$1*` ] && ln -s $cim_bin_path/$1-$2 $cim_bin_path/$1
    rm $cim_tmp_path/resume-$1-$2
    echo "Install done"
    return 0
}


if [ -n "$1" ];then
    case $1 in
	clisp*|gcl*|ecl*)
	    cim_start_impl_install `__cim_split_impl_version $1`
	    ;;
	abcl*)
	    
	    ;;
	sbcl*)
	    
	    ;;
	ccl*)
	    
	    ;;
	*)
	    echo "Unknown Lisp impl $1. Exit." >&2
	    exit 1;
	    ;;
    esac
fi

