#!/bin/sh
cim_get_donload_path(){
    impl=$1
    version=$2
    case $impl in
    clisp)
	    echo http://ftp.gnu.org/pub/gnu/clisp/release/${version}/$impl-$version.tar.gz
	    ;;
	*)
	    echo "unsupproted" >&2;
	    exit 1
	    ;;
    esac
}

cim_start_impl_install(){
    impl=$1
    version=$2
    install_dir=$cim_impls_path/$impl-$version
    [ -d $install_dir ] && (echo "It seems you have installed clisp-$version. Exit." >&2 ; exit 1; )
    impl_download $impl $version
}
cim_download_impl(){
    impl=$1
    version=$2
    impl_archive=$impl-$version.tar.gz
    rm -rf $impl_archive
    curl `get_donload_path $impl $version` -o $cim_archives_path/$impl_archive
    cim_expand_impl $impl $version
}

cim_expand_impl(){
    impl=$1
    version=$2
    rm -rf  $cim_src_path/$impl-$version
    gzip -dc $cim_archives_path/$impl-$version.tar.gz | tar xf - -C $cim_src_path
    cim_configure_impl $impl $version
}

cim_configure_impl(){
    impl=$1
    version=$2
    cd $cim_src_path/$impl-$version
    install_dir=$cim_impls_path/$impl-$version
    mkdir -p $install_dir
    ./configure --prefix=$install_dir
    cim_make_impl $impl $version
}
cim_make_impl(){
    impl=$1
    version=$2
    make
    cim_install_impl $impl $version
}
cim_install_impl(){
    impl=$1
    version=$2
    make install
    cim_finish_install_impl $impl $version
}
cim_finish_install_impl(){
    impl=$1
    version=$2
    ln -s $cim_impls_path/$impl-$version/bin/$impl $cim_bin_path/$impl-$version
    echo "Install done"
    return 0
}
