#!/bin/sh -
# This file is for execute
set -x
if [ -L "$CIM_HOME/bin/$1" ] &&
    find -L "$CIM_HOME/bin/" -name "$1" -path "$CIM_HOME/impls/"
then
    . "$CIM_HOME/scripts/cim_utils"
    lisp_impl=`echo "$1" | cut -d- -f 1`
    lisp_full_name=`__cim_split_impl_version $1 | tr \  -`
    rm -f "$CIM_HOME/bin/$lisp_impl"
    ln -s "$CIM_HOME/bin/$lisp_full_name" "$CIM_HOME/bin/$lisp_impl"
elif lisp_full_name=`which "$1"`;then
    lisp_impl=`basename "$lisp_full_name"`
    rm -f "$CIM_HOME/bin/$lisp_impl"
    ln -s "$lisp_full_name" "$CIM_HOME/bin/${lisp_impl}-system"
    ln -s "$CIM_HOME/bin/${lisp_impl}-system" "$CIM_HOME/bin/$lisp_impl"
else
    echo "$1 is not installed. See 'cim list use."
    exit 1
fi
echo "lisp_impl=$lisp_impl" > "$CIM_HOME/config/current"
