#!/bin/sh -
. "$CIM_HOME/scripts/cim_utils"
if [ "$1" = "" ];then
    cim_error "Please specify command."
    exit 1
elif [ -s "$CIM_HOME/scripts/cim_cmd_list_$1" ];then
    sh "$CIM_HOME/scripts/cim_cmd_list_$1"
elif [ -s "$CIM_HOME/scripts/cim_cmd_$1" ];then
    cim_error "'$1' doesn't take target."
else
    cim_error "Unknown subcommand '$1'. See 'cim help list'."
    exit 1
fi
