#!/bin/sh -
# This file is for execute
set -e
: ${CIM_HOME:="$HOME/.cim"};
export CIM_HOME
umask 077
mkdir -p "$CIM_HOME/archives"
mkdir -p "$CIM_HOME/tmp"
download(){
    if which curl > /dev/null ;then
	curl -L "$1"
    elif which wget > /dev/null ;then
	wget  -O - "$1"
    elif which fetch > /dev/null;then
	fetch -o - "$1"
    fi
}
download https://codeload.github.com/KeenS/CIM/tar.gz/master | gzip -cd - | tar -xf - -C "$CIM_HOME/tmp"
for dir in lib scripts res ;do
    rm -rf "$CIM_HOME/$dir"
done
mv "$CIM_HOME/tmp/CIM-master/"* "$CIM_HOME/" &&
rm -rf "$CIM_HOME/tmp/CIM-master/"
for dir in archives bin config cores impls lib res scripts src sysets tmp
do
    mkdir -p "$CIM_HOME/$dir"
done
rm -f "$CIM_HOME/bin/cl"
ln -s "$CIM_HOME/scripts/cl" "$CIM_HOME/bin/cl"
rm -f "$CIM_HOME/bin/ql"
ln -s "$CIM_HOME/scripts/ql" "$CIM_HOME/bin/ql"
chmod u+x "$CIM_HOME/scripts/cl"
chmod u+x "$CIM_HOME/scripts/ql"
touch ~/.lisprc
cat <<EOF > "$CIM_HOME/init"
#!/bin/sh
: \${CIM_HOME:="$CIM_HOME"};
export CIM_HOME
PATH="\$CIM_HOME/bin:\$PATH";export PATH
if [ -s "\$CIM_HOME/config/default" ];then
    rm -f "\$CIM_HOME/config/current"
    cp "\$CIM_HOME/config/default" "\$CIM_HOME/config/current"
fi

. "\$CIM_HOME/scripts/cim"

EOF

cat <<EOM
Adding to your .*rc file
'[ -s $HOME/.cim/init ] && . $HOME/.cim/init'
EOM
cimrc='[ -s "$HOME/.cim/init" ] && . "$HOME/.cim/init"'
if [ -n "$BASH_VERSION" ];then
    echo "$cimrc" >> "$HOME/.bashrc"
fi
if [ -n "$ZSH_VERSION" ];then
    echo "$cimrc" >> "$HOME/.zshrc"
fi
  
