#!/bin/sh -

[ -s "$CIM_HOME/config/default" ] &&
. "$CIM_HOME/config/default" &&
default="$LISP_IMPL"

[ -s "$CIM_HOME/config/current.$CIM_ID" ] &&
. "$CIM_HOME/config/current.$CIM_ID" &&
current="$LISP_IMPL"


. "$CIM_HOME/scripts/cim_utils"
cim_aware_system_lisp
cat <<EOF
PATH = $PATH

CIM_ID   = $CIM_ID
CIM_HOME = $CIM_HOME

current lisp = $current
default lisp = $default

EOF
for impl in $impls; do
    eval detail=\$$impl
    if [ -n "$detail" ]; then
        printf "%-5s = %s\n" "$impl" "$detail"
    fi
done
echo 
for impl in `find $CIM_HOME/bin/ -name '*-system' -exec basename '{}' ';'  2> /dev/null `;do
    printf "%-12s = %s\n" "$impl" `PATH=/bin:/usr/bin:/usr/local/bin which ${impl%-system} 2> /dev/null`
done
