#!/bin/sh -
# This file is for execute

set -xe

. "$CIM_HOME/scripts/cim_install_impl_lib"

cim_install_full="
cim_install_impl_start
cim_install_impl_download
cim_install_impl_expand
cim_install_impl_configure
cim_install_impl_make
cim_install_impl_doc
cim_install_impl_install
cim_install_impl_finish
"
cim_install_sbcl_full="
cim_install_impl_start
cim_install_impl_download
cim_install_impl_expand
cim_install_sbcl_ensure_impl
cim_install_sbcl_make
cim_install_impl_make_doc
cim_install_sbcl_install
cim_install_impl_finish
"

cim_install_ccl_full="
cim_install_impl_start
cim_install_impl_download
cim_install_impl_expand
cim_install_ccl_rebuild_full
cim_install_ccl_install
cim_install_impl_finish
"

cim_install_abcl_full="
cim_install_impl_start
cim_install_impl_download
cim_install_impl_expand
cim_install_abcl_install
cim_install_impl_finish
"

cim_install_alisp_full="
cim_install_impl_start
cim_install_impl_download
cim_install_impl_expand
cim_install_alisp_install
cim_install_impl_finish
"

target="$1"
shift
set -e --  `__cim_split_impl_version "$target"` "$@"
case "$target" in
    clisp*|gcl*|ecl*)
	processes="$cim_install_full"
	;;
    abcl*)
	processes="$cim_install_abcl_full"
	;;
    sbcl*)
	processes="$cim_install_sbcl_full"
	;;
    ccl*)
	processes="$cim_install_ccl_full"
	;;
    alisp*)
	processes="$cim_install_alisp_full"
	;;
    *)
	echo "Unknown Lisp impl $1. Exit." >&2
	continue
	;;
esac
    
printf "%s\n" $processes > "$CIM_HOME/tmp/resume-$1-$2"
for proc in $processes;do
    eval $proc "$@" && [ -e "$CIM_HOME/tmp/resume-$1-$2" ] && sed -i -e "/$proc/d" "$CIM_HOME/tmp/resume-$1-$2"
done
