#!/bin/sh -
# This file is for execute

. "$CIM_HOME/scripts/cim_utils"
cim_aware_system_lisp
impls=""
if [ "$1" = "all" ];then
    impls=`cim list use`
    shift
elif [ "$1" = "impls" ];then
    impls=`find "$CIM_HOME/bin" -mindepth 1 ! -name '*-*' ! -name 'cl' ! -name 'ql' ! -name 'cim' -exec basename '{}' ';'  2> /dev/null | sort`
    shift
else
    installed=`cim list use`
    installed="$installed
"
    while [ "$1" != "do" ];do
	if echo "$installed" | grep -xF "$1" > /dev/null 2>&1;then
	    impls="$impls $1"
	else
	    echo "$1 is not installed." >&2
	    exit 1
	fi
	if [ "$#" -gt 0 ];then
	    shift
	else
	    echo "Missing 'do'." >&2
	    exit 1
	fi
    done
fi
if [ "$1" != do ];then
    echo "$1 is found where 'do' is expected"
    exit 1
fi
shift

for impl in $impls;do
    cim_green ">>>$impl $@"
    LISP_IMPL="$impl" cl "$@"
    cim_green "<<<"
done
