#!/bin/sh -
. "$CIM_HOME/scripts/cim_utils"
case "$1" in
    "")
	cat "$CIM_HOME/res/cim_help" ;;
    *)
	if [ -s "$CIM_HOME/res/cim_help_$1" ];then
	    cat "$CIM_HOME/res/cim_help_$1"
	else
	    cim_error "Help for '$1' is not prepared, sorry."
	    return 1
	fi
	;;
esac
