#!/bin/sh -
# This file is for execute
set -e

. "$CIM_HOME/scripts/cim_lib_install"

cim_install_full="
__start
__download
__expand
__configure
__make
__doc
__install
__link
__config_cim
__install_ql_if_need
"
cim_install_sbcl_full="
__start
__download
__expand
__sbcl_ensure_impl
__sbcl_make
__make_doc
__sbcl_install
__link
__config_cim
__install_ql_if_need
"

cim_install_ccl_full="
__start
__download
__expand
__ccl_rebuild_full
___ccl_install
__link
__config_cim
__install_ql_if_need
"

cim_install_abcl_full="
__start
__download
__expand
__abcl_install
__link
__config_cim
__install_ql_if_need
"

cim_install_alisp_full="
__start
__download
__expand
__alisp_install
__link
__config_cim
__install_ql_if_need
"

target="$1"
shift
set -e --  `__cim_split_impl_version "$target"` "$@"
case "$target" in
    clisp*|gcl*|ecl*)
	processes="$cim_install_full"
	;;
    abcl*)
	processes="$cim_install_abcl_full"
	;;
    sbcl*)
	processes="$cim_install_sbcl_full"
	;;
    ccl*)
	processes="$cim_install_ccl_full"
	;;
    alisp*)
	processes="$cim_install_alisp_full"
	;;
    *)
	echo "Unknown Lisp impl $1. Exit." >&2
	continue
	;;
esac
    
printf "%s\n" $processes > "$CIM_HOME/tmp/resume-$1-$2"
for proc in $processes;do
    eval $proc "$@" && sed -i -e "/$proc/d" "$CIM_HOME/tmp/resume-$1-$2"
done
rm -f "$CIM_HOME/tmp/resume-$1-$2"
echo "Install done"
