#!/bin/sh -
# This file is for execute
sh "$CIM_HOME/scripts/cim_aware_system_lisp"

if [ -L "$CIM_HOME/bin/$1" ] && {
	find -L "$CIM_HOME/bin/" -name "$1" -path "$CIM_HOME/impls/" ||
	expr match "$1" '*-system'
    }
then
    . "$CIM_HOME/scripts/cim_utils"
    lisp_impl=${1%-*}
    lisp_full_name=`__cim_split_impl_version $1 | tr \  -`
    rm -f "$CIM_HOME/bin/$lisp_impl"
    ln -s "$CIM_HOME/bin/$lisp_full_name" "$CIM_HOME/bin/$lisp_impl"
else
    echo "$1 is not installed. See 'cim list use."
    exit 1
fi
echo "lisp_impl=$lisp_impl" > "$CIM_HOME/config/current.$CIM_ID"
