#!/bin/sh -
# This file is for execute
. "$CIM_HOME/scripts/cim_utils"

while [ $# -gt 0 ];do
    if [ "$1" = "all" ] ;then
	set -- `cim list distclean| grep -v '\(Subcommand\|^#\)'`
	continue
    fi
    target=`cim_normarize_impl_version "$1"`
    if [ -z "$target" ]; then
        cim_error "Error: cim_cmd_distclean: invalid argument '$1'"
        exit 1
    fi
    if [ -d "$CIM_HOME/impls/$target" ];then
	case "$1" in
	    ecl*|gcl*)
		(cd "$CIM_HOME/src/$target" && make clean)
		;;
	    clisp*)
		(cd "$CIM_HOME/src/$target/src" && make clean)
		;;
	    ccl*|abcl*|alisp*)
		;;
	    sbcl)
		(cd "$CIM_HOME/src/$target" && sh clean.sh)
		;;
	esac
    else
	cim_error "Src of $target was not found."
    fi
    shift
done
