#!/bin/sh -
# This file is for execute
. "$CIM_HOME/scripts/cim_utils"

while [ $# -gt 0 ];do
    if [ "$1" = "all" ] ;then
	set -- `cim list clean | grep -v '\(Subcommand\|^#\)'`
	continue
    fi
    rm -rf "$CIM_HOME/archives/$1"
    rm -rf "$CIM_HOME/src/$1"
    shift
done
