#!/bin/sh -
status=0
. "$CIM_HOME/scripts/cim_utils"
if [ $# -gt 0 ];then
    for resume in "$@";do
	if [ "$resume" = "all" ]; then
	    set -- `cim list resume rm | grep -v '\(Subcommand\|^#\)'`
	    continue
	fi
	resume=`cim_normalize_impl_version "$1"`

	if [ -f "$CIM_HOME/res/resume-$resume" ];then
	    rm "$CIM_HOME/res/resume-$resume"
	else
	    cim_error "Unknown resume $resume."
	    status=`expr $status + 1`
	fi
    done
else
    cim_error "Please specify what to rm. To get the list, use 'cim list resume rm'."
    exit 1
fi
exit $status
