#!/bin/sh -
# This file is for execute
. "$CIM_HOME/scripts/cim_utils"

while [ $# -gt 0 ];do
    if [ "$1" = "all" ] ;then
	set -- `cim list distclean| grep -v '\(Subcommand\|^#\)'`
	continue
    fi
    impl=`__cim_split_impl_version "$1" | tr \  -`
    if [ -d "$CIM_HOME/impls/$impl" ];then
	case "$1" in
	    ecl*|gcl*)
		(cd "$CIM_HOME/src/$impl" && make clean)
		;;
	    clisp*)
		(cd "$CIM_HOME/src/$impl/src" && make clean)
		;;
	    ccl*|abcl*)
		;;
	    sbcl)
		(cd "$CIM_HOME/src/$impl" && sh clean.sh)
		;;
	esac
    else
	 "Src of $impl was not found." >&2
    fi
    shift
done
