#!/bin/sh -
# This file is for execute
case "$1" in
    rm) shift
	sh "$CIM_HOME/scripts/cim_cmd_resume_rm" "$@"
	;;
    *)
	. "$CIM_HOME/scripts/cim_lib_install"
	IN_RESUME=1
	while [ $# -gt 0 ];do
	    if [ "$1" = "all" ];then
		set -- `cim list resume | grep -v '\(Subcommand\|^#\)'`
		continue
	    else
		if [ -s "$CIM_HOME/tmp/resume-$1" ]; then
		    resume="$1"
		    set -- `__cim_split_impl_version ${resume#resume-}`
		    for proc in `cat "$resume"`; do
			eval $proc "$@" && [ -s "$CIM_HOME/tmp/resume-$1-$2" ] && sed -i -e "/$proc/d" "$CIM_HOME/tmp/resume-$1-$2" ||
			exit 1
		    done

		    shift
		else
		    echo "Cannot resume $1. Cannot find resume file." >&2
		fi
	    fi
	done
	;;
esac

