#!/bin/sh -
# This file is for execute
case "$1" in
    rm) shift
	sh "$CIM_HOME/scripts/cim_cmd_resume_rm" "$@"
	;;
    *)
	. "$CIM_HOME/scripts/cim_lib_install"
	IN_RESUME=1;export IN_RESUME
	while [ $# -gt 0 ];do
	    if [ "$1" = "all" ];then
		set -- `cim list resume | grep -v '\(Subcommand\|^#\)'`
		continue
	    else
		. "$CIM_HOME/scripts/cim_utils"
		target=`cim_normarize_impl_version "$1"`
		if [ -s "$CIM_HOME/tmp/resume-$target" ]; then
		    resume="$CIM_HOME/tmp/resume-$target"
		    impl=${target%-*}
		    version=${target#*-}
		    for proc in `cat "$resume"`; do
			{
			    $proc "$impl" "$version" &&
			    [ -s "$resume" ] &&
			    sed -e "/$proc/d" "$resume" > "$resume.tmp" &&
			    mv "$resume.tmp" "$resume"
			} || exit 1
		    done
		    rm -f "$CIM_HOME/tmp/resume-$1-$2"
		    shift
		elif [ -e "$CIM_HOME/tmp/resume-$target" ];then
		    rm -f "$CIM_HOME/tmp/resume-$1-$2"
		    shift
		else
		    echo "Cannot resume $1. Cannot find resume file." >&2
		    exit 1
		fi
	    fi
	done
	;;
esac

