#!/bin/sh -
# This file is for execute

[ -n "$CIM_HOME" ] &&
cd "$CIM_HOME" &&
for dir in archives cores impls src sysets tmp bin; do
    rm -rf "$dir"
    mkdir -p "$dir"
done
ln -s "$CIM_HOME/scripts/cl" "$CIM_HOME/bin/"
ln -s "$CIM_HOME/scripts/ql" "$CIM_HOME/bin/"
