#!/bin/sh -
{
    find "$CIM_HOME/src/" "$CIM_HOME/log/" -mindepth 1 -maxdepth 1 -type d  -exec basename '{}' ';'
    find "$CIM_HOME/archives/" -mindepth 1 -maxdepth 1 -exec basename '{}' ';' |
        while read -r archive; do
            echo ${archive%%.tar.*}
        done
    
} | sort --unique
