#!/bin/sh -
set -e
. "$CIM_HOME/scripts/cim_utils"
# :FIXME: cim_split_impl_version is used to validate argument
if ! cim_split_impl_version "$1" > /dev/null 2>&1 ; then
    cim_error "Error: cim_cmd_install: invalid argument '$1'"
    exit 1
fi



. "$CIM_HOME/scripts/cim_lib_install"

cim_install_full="
__start
__download
__expand
__configure
__make
__doc
__install
__link
__config_cim
__install_ql_if_need
"
cim_install_sbcl_full="
__start
__download
__expand
__sbcl_ensure_impl
__sbcl_make
__doc
__sbcl_install
__link
__config_cim
__install_ql_if_need
"

cim_install_ccl_full="
__start
__download
__expand
__ccl_rebuild_full
__ccl_install
__link
__config_cim
__install_ql_if_need
"

cim_install_abcl_full="
__start
__download
__expand
__abcl_install
__link
__config_cim
__install_ql_if_need
"

cim_install_alisp_full="
__start
__download
__expand
__alisp_install
__link
__config_cim
__install_ql_if_need
"

target="$1"
shift
set -e
set  --  `cim_split_impl_version "$target"` "$@"

case "$target" in
    clisp*|gcl*|ecl*)
	processes="$cim_install_full"
	;;
    abcl*)
	processes="$cim_install_abcl_full"
	;;
    sbcl*)
	processes="$cim_install_sbcl_full"
	;;
    ccl*)
	processes="$cim_install_ccl_full"
	;;
    alisp*)
	processes="$cim_install_alisp_full"
	;;
    *)
	cim_error "Unknown Lisp impl $1. Exit."
        exit 1
	;;
esac
    
printf "%s\n" $processes > "$CIM_HOME/tmp/resume-$1-$2"
for proc in $processes;do
    {
	$proc "$@" && 
	sed -e "/$proc/d" "$CIM_HOME/tmp/resume-$1-$2" > "$CIM_HOME/tmp/resume-$1-$2.tmp" &&
	mv "$CIM_HOME/tmp/resume-$1-$2.tmp" "$CIM_HOME/tmp/resume-$1-$2"
    } || exit 1
done
rm -f "$CIM_HOME/tmp/resume-$1-$2"
cim_message "Install done"
