#!/bin/sh -

. "$CIM_HOME/scripts/cim_utils"
cim_aware_system_lisp
cim_register_all_impls
if [ "$1" = "default" ];then
    if [ -s "$CIM_HOME/config/default" ];then
	. "$CIM_HOME/config/default"
	set - "$LISP_IMPL"
    else
	echo "Default lisp is not set. Please 'cim use <impl> --default first."
	exit 1
    fi
fi
. "$CIM_HOME/config/current.$CIM_ID"
impl="${1%-*}"
lisp_full_name=`normarize_impl_version "$1"`

if [ ! -L "$CIM_HOME/bin/$lisp_full_name" ]; then
    echo "$1 is not installed. See 'cim list use'."
    exit 1
fi
echo "LISP_IMPL=$lisp_full_name" > "$CIM_HOME/config/current.$CIM_ID"
for var in $abcl $alisp $ccl $clisp $ecl $gcl $sbcl;do
    if [ "${var%-*}" = "$impl" ];then
	echo "${var%-*}=$lisp_full_name"
    else
	echo "${var%-*}=$var"
    fi
done >> "$CIM_HOME/config/current.$CIM_ID"

if [ "$2" = "--default" ];then
    cp "$CIM_HOME/config/current.$CIM_ID" "$CIM_HOME/config/default"
fi
