#!/bin/sh -
# This file is for execute
. "$CIM_HOME/scripts/cim_utils"

while [ $# -gt 0 ];do
    if [ "$1" = "all" ] ;then
	set -- `cim list clean | grep -v '\(Subcommand\|^#\)'`
	continue
    fi
    target=`cim_normarize_impl_version "$1"`
    if [ -z "$target" ]; then
        cim_error "Error: cim_cmd_clean: invalid argument '$1'"
        exit 1
    fi
    if ! { [ -e "$CIM_HOME/archives/$target" ] ||
               [ -e "$CIM_HOME/src/$target" ] ||
               [ -e "$CIM_HOME/log/$target" ];}; then
        cim_error "$target is not installed"
        exit 1
    fi

    rm -rf "$CIM_HOME/archives/$target"
    rm -rf "$CIM_HOME/src/$target"
    rm -rf "$CIM_HOME/log/$target"
    shift
done
