#!/bin/sh -
# This file is for execute
if [ -z "$LISP_IMPL" ];then
    . "$CIM_HOME/config/current.$CIM_ID"
    export LISP_IMPL
fi
if tput=`which tput 2> /dev/null`;then
    COLUMNS=`$tput cols`
    export COLUMNS
fi
use_rl=false
for ARG;do
   { [ "$ARG" = "--repl" ] || [ "$ARG" = "-r" ]; } && use_rl=true
done
for ARG;do
    [ "$ARG" = "--no-rl" ] && use_rl=false
done

load_file="$CIM_HOME/lib/script.lisp"
if [ "$use_rl" = true ] && rlwrap=`which rlwrap 2> /dev/null`;then
    rlwrap="$rlwrap -c -H $HOME/.lisp_history -i -q \" -r "
fi

case "$LISP_IMPL" in
    sbcl*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" --noinform --no-sysinit --no-userinit --non-interactive --load "$load_file" -- "$@"
	;;
    clisp*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" -norc --quiet --silent -on-error exit -i "$load_file" -- "$@"
	;;
    ecl*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" -norc -q -shell "$load_file" -- "$@"
	;;
    ccl*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" --no-init --quiet --batch --load "$load_file" -- "$@"
	;;
    gcl*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" -batch -load "$load_file" -- "$@"
	;;
    abcl*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" --noinform --noinit --nosystem --batch --load "$load_file" -- "$@"
	;;
    alisp*)
	exec $rlwrap "$CIM_HOME/bin/$LISP_IMPL" --qq -L "$load_file" --kill -- "$@"
	;;
    "")
	echo "\$LISP_IMPL is not set. Have you loaded ~/.cim/init ?" >&2
	exit 1
	;;
    *)
	echo "Unknown lisp implementation $LISP_IMPL. Exit." >&2
	exit 1
	;;
esac

