#!/bin/sh -
# This file is for execute
. "$CIM_HOME/config/current"
cl_init_file="$HOME/.lisprc"
lib_repl="$CIM_HOME/lib/repl.lisp"
rlwrap=`which rlwrap`
while getopts ":adhe:FlnpL:Sv" frag;do
    case "$frag" in
	a) cl_autosplit=true;;
	d) cl_debug=true;;
	h) cl_print_help; exit 0;;
	e) cl_sexp="$cl_sexp $OPTARG";cl_sexp_p=true;;
	F) cl_IFS="$OPTARG";;
	l) cl_lineend=true;;
	n) cl_eachline=true;;
	p) cl_printline=true;;
	L) cl_load_systems="$OPTARG";;
	S) cl_script_path=true;;
	v) cl_print_version; exit 0;;
    esac
done
cl_sexp="(progn $cl_sexp (values))"
shift $(( $OPTIND - 1 ))
if [ -z "$cl_sexp_p" ] && [ -f "$1" ]; then
    cl_file="$1"
    shift
fi
case "$lisp_impl" in
    sbcl)
	if [ -n "$cl_sexp_p" ]; then
	    exec "$CIM_HOME/bin/sbcl" --noinform --no-sysinit --non-interactive --userinit "$cl_init_file" --eval "$cl_sexp"
	elif [ -n "$cl_file" ]; then
	    exec "$CIM_HOME/bin/sbcl" --noinform --no-sysinit --userinit "$cl_init_file" --script "$cl_file"
	else
	    exec "$rlwrap" "$CIM_HOME/bin/sbcl" --noinform --no-sysinit --userinit "$cl_init_file" --script "$lib_repl"
	fi
	;;
    clisp)
	if [ -n "$cl_sexp_p" ]; then
	    exec "$CIM_HOME/bin/clisp" -norc --quiet --silent -on-error exit -i "$cl_init_file" -x "$cl_sexp"
	elif [ -n "$cl_file" ]; then
	    exec "$CIM_HOME/bin/clisp" -norc --quiet --silent -on-error exit -i "$cl_init_file" "$cl_file"
	else
	    exec "$rlwrap" "$CIM_HOME/bin/clisp" -norc --quiet --silent -on-error exit -i "$cl_init_file" "$lib_repl"
	fi
	;;
    ecl)

	if [ -n "$cl_sexp_p" ]; then
	    exec "$CIM_HOME/bin/ecl" -norc -q -load "$cl_init_file" -eval "$cl_sexp" -eval "(quit)"
	elif [ -n "$cl_file" ]; then
	    exec "$CIM_HOME/bin/ecl" -norc -q -load "$cl_init_file" -shell  "$cl_file"
	else
	    exec "$rlwrap" "$CIM_HOME/bin/ecl" -norc -q -load "$cl_init_file" -shell "$lib_repl"
	fi
	;;
    ccl)
	if [ -n "$cl_sexp_p" ]; then
	    exec "$CIM_HOME/bin/ccl" --no-init --quiet --batch --load "$cl_init_file" --eval "$cl_sexp" --eval '(quit)' 
	elif [ -n "$cl_file" ]; then
	    exec "$CIM_HOME/bin/ccl" --no-init --quiet --batch --load "$cl_init_file" --load "$cl_file" --eval '(quit)'
	else
	    exec "$rlwrap" "$CIM_HOME/bin/ccl"  --no-init --quiet --batch --load "$cl_init_file" --load "$lib_repl"
	fi
	;;
    gcl)
	if [ -n "$cl_sexp_p" ]; then
	    exec "$CIM_HOME/bin/gcl" -batch -load "$cl_init_file" -eval "$cl_sexp" -- "$@"
	elif [ -n "$cl_file" ]; then
	    exec "$CIM_HOME/bin/gcl" -load "$cl_init_file" -f "$cl_file" -- "$@"
	else
	    exec "$rlwrap" "$CIM_HOME/bin/gcl" -load "$cl_init_file" -f "$lib_repl" -- "$@"
	fi
	;;
    abcl)
	if [ -n "$cl_sexp_p" ]; then
	    exec "$CIM_HOME/bin/abcl" --noinform --noinit --system --load "$cl_init_file" --batch --eval "$cl_sexp"
	elif [ -n "$cl_file" ]; then
	    exec "$CIM_HOME/bin/abcl" --noinform --noinit --system --load "$cl_init_file" --batch --load "$cl_file"
	else
	    exec "$CIM_HOME/bin/abcl" --noinform --noinit --system --load "$cl_init_file" --batch --load "$lib_repl"
	fi
	cl_command="java -jar $CIM_HOME/bin/abcl.jar --noinform --noinit --nosystem"
	cl_batch="--batch"
	cl_eval="--eval"
	cl_load="--load"
	cl_quit="$cl_eval '(quit)'"
	;;
    alisp)
	if [ -n "$cl_sexp_p" ]; then
	    exec alisp --qq -L "$cl_init_file" -e "$cl_sexp" --kill
	elif [ -n "$cl_file" ]; then
	    exec alisp --qq -L "$cl_init_file" -L "$cl_file" --kill
	else
	    exec "$rlwrap" "$CIM_HOME/bin/alisp" --qq -L "$cl_init_file" -L "$lib_repl" --kill
	fi
	;;
    "")
	echo "\$LISP_IMPL is not set. Have you loaded ~/.cim/scripts/cim ?" >&2
	exit 1
	;;
    *)
	echo "Unknown lisp implementation $LISP_IMPL. Exit." >&2
	exit 1
	;;
esac

