#!/bin/sh -
if [ -n "$ECL" ];then
    if [ ! -L "$CIM_HOME/bin/$ECL" ];then
	echo "$ECL is not installed"
	exit 1
    fi
    if ! expr "$ECL" : 'ecl.*' > /dev/null 2>&1 ;then
	echo "$ECL is not a ecl"
	exit 1
    fi
    ecl="$ECL"
else
    if [ -z "$CIM_ID" ]; then
        . "$CIM_HOME/config/default"
    else
        . "$CIM_HOME/config/current.$CIM_ID"
    fi
fi
exec "$ecl" "$@"
