#!/bin/sh -
if [ -n "$GCL" ];then
    if [ ! -L "$CIM_HOME/bin/$GCL" ];then
	echo "$GCL is not installed"
	exit 1
    fi
    if ! expr "$GCL" : 'gcl.*' > /dev/null 2>&1;then
	echo "$GCL is not a gcl"
	exit 1
    fi
    gcl="$GCL"
else
    . "$CIM_HOME/config/current.$CIM_ID"
fi
exec "$gcl" "$@"
