#!/bin/sh -
: ${CIM_HOME:=`cd \`dirname "$0"\`/../; pwd`}
if [ -n "$LISP" ];then
    if ! expr "$LISP" : 'lisp.*' > /dev/null 2>&1 ;then
	echo "$LISP is not a lisp"
	exit 1
    fi
    if [ ! -L "$CIM_HOME/bin/$LISP" ];then
	echo "$LISP is not installed"
	exit 1
    fi
    lisp="$LISP"
else
    if [ -z "$CIM_ID" ]; then
        . "$CIM_HOME/config/default"
    else
        . "$CIM_HOME/config/current.$CIM_ID"
    fi
fi
exec "$CIM_HOME/bin/$lisp" "$@"
