#!/bin/sh
if [ "$#" = 0 ];then
    sh "$CIM_HOME/scripts/ql_cmd_help"
    exit 1
fi
command=$1
shift
case $command in
    quickload|install)
	cl "$CIM_HOME/scripts/ql_cmd_install" "$@"
	;;
    uninstall)
	cl "$CIM_HOME/scripts/ql_cmd_uninstall" "$@"
	;;
    update)
	cl "$CIM_HOME/scripts/ql_cmd_update" "$@"
	;;
    list)
	cl "$CIM_HOME/scripts/ql_cmd_list" "$@"
	;;
    system-apropos|search)
	cl "$CIM_HOME/scripts/ql_cmd_search" "$@"
	;;
    deps)
	cl --no-init -- "$CIM_HOME/scripts/ql_cmd_deps" "$@"
	;;
    help)
	sh "$CIM_HOME/scripts/ql_cmd_help" "$@"
	;;
	*)
	echo "Unknown command $command." >&2
        sh "$CIM_HOME/scripts/ql_cmd_help"
	exit 1
	;;
esac
