#!/bin/sh

command=$1
shift
case $command in
    install)
	cl "$CIM_HOME/scripts/ql_install" "$@"
	;;
    uninstall)
	cl "$CIM_HOME/scripts/ql_uninstall" "$@"
	;;
    upgrade)
	if [ -n "$1" ];then
	    "$CIM_HOME/bin/cl" -e "`wrap_all '(ql:update-dist :' ')' $@`"
	else
	    "$CIM_HOME/bin/cl" -e '(ql:update-all-dists)'
	fi
	;;
    search)
	cl "$CIM_HOME/scripts/ql_search" "$@"
	;;
    system-apropos)
	ql search "$@"
	;;
    quickload)
	ql install "$@"
	;;
	*)
	echo "Unknown command $command. Exit." >&2
	exit 1
	;;
esac
