#!/bin/sh

wrap_all(){
    before="$1"
    after="$2"
    shift 2
    while [ $# -gt 0 ] ; do
	sexp="${before}$1${after}"
	shift
    done
    echo "$sexp"
}
command=$1
shift
case $command in
    install)
	"$CIM_HOME/bin/cl" -e "`wrap_all '(ql:quickload :' ')' $@`"
	;;
    uninstall)
	"$CIM_HOME/bin/cl" -e "`wrap_all '(ql:uninstall-dist \"' '\")' $@`"
	;;
    upgrade)
	if [ -n "$1" ];then
	    "$CIM_HOME/bin/cl" -e "`wrap_all '(ql:update-dist :' ')' $@`"
	else
	    "$CIM_HOME/bin/cl" -e '(ql:update-all-dists)'
	fi
	;;
    system-apropos)
	"$CIM_HOME/bin/cl" -e "(ql:system-apropos \"$1\")"
	;;
    search)
	"$CIM_HOME/bin/ql" system-apropos "$@"
	;;
    install)
	"$CIM_HOME/bin/ql" quickload "$@"
	;;
	*)
	echo "Unknown command $command. Exit." >&2
	exit 1
	;;
esac
