'\" t
.\"     Title: cim-version
.\"    Author: keen(@blackenedgold) 3han5chou7@gmail.com
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/17/2015
.\"    Manual: CIM Manual
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CIM\-VERSION" "1" "01/17/2015" "\ \&" "CIM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cim-version \- Show the version
.SH "SYNOPSIS"
.sp
.nf
cim version
.fi
.SH "DESCRIPTION"
.sp
Show current cim\(cqs version\&. The version is the Unix time of release point\&.
.SH "EXSAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
show the version
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
$ cim version
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.PP
\fBkeen(@blackenedgold) 3han5chou7@gmail\&.com\fR
.RS 4
Author.
.RE
